import type { SportEvent } from '@/types/events/type'

export function generateDummyMatches(): SportEvent[] {
  return [
    {
        idEvent: '1',
        strEvent: 'Arsenal vs Manchester United',
        strSport: 'Soccer',
        strHomeTeam: 'Arsenal',
        strAwayTeam: 'Manchester United',
        intHomeScore: '0',
        intAwayScore: '0',
        strHomeTeamBadge: 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
        strAwayTeamBadge: 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg',
        strStatus: 'Live',
        minute: 0,
        idAPIfootball: null,
        strEventAlternate: null,
        strFilename: null,
        idLeague: '',
        strLeague: '',
        strLeagueBadge: null,
        strSeason: '',
        strDescriptionEN: null,
        intRound: null,
        intSpectators: null,
        strOfficial: null,
        strTimestamp: null,
        dateEvent: '',
        dateEventLocal: '',
        strTime: null,
        strTimeLocal: null,
        strGroup: null,
        idHomeTeam: '',
        idAwayTeam: '',
        intScore: null,
        intScoreVotes: null,
        strResult: null,
        idVenue: null,
        strVenue: null,
        strCountry: null,
        strCity: null,
        strPoster: null,
        strSquare: null,
        strFanart: null,
        strThumb: null,
        strBanner: null,
        strMap: null,
        strTweet1: null,
        strVideo: null,
        strPostponed: null,
        strLocked: null
    },
    {
        idEvent: '2',
        strEvent: 'Chelsea vs Liverpool',
        strSport: 'Soccer',
        strHomeTeam: 'Chelsea',
        strAwayTeam: 'Liverpool',
        intHomeScore: '0',
        intAwayScore: '0',
        strHomeTeamBadge: 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',
        strAwayTeamBadge: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',
        strStatus: 'Live',
        minute: 0,
        idAPIfootball: null,
        strEventAlternate: null,
        strFilename: null,
        idLeague: '',
        strLeague: '',
        strLeagueBadge: null,
        strSeason: '',
        strDescriptionEN: null,
        intRound: null,
        intSpectators: null,
        strOfficial: null,
        strTimestamp: null,
        dateEvent: '',
        dateEventLocal: '',
        strTime: null,
        strTimeLocal: null,
        strGroup: null,
        idHomeTeam: '',
        idAwayTeam: '',
        intScore: null,
        intScoreVotes: null,
        strResult: null,
        idVenue: null,
        strVenue: null,
        strCountry: null,
        strCity: null,
        strPoster: null,
        strSquare: null,
        strFanart: null,
        strThumb: null,
        strBanner: null,
        strMap: null,
        strTweet1: null,
        strVideo: null,
        strPostponed: null,
        strLocked: null
    }
  ]
}